# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3bf48dcc71c9fe99a0b979d68215b05e09410823bec2377b5f32c2fada2e43211419c1f4b8c0bc3ec50d250f505d940c71962b14540b1d65068a13ae6dbf721

test:
  secret_key_base: 70f3542dbb83fa82d2e2b0ffbbb0e357610a7a38b6f140acc09b1ed5415b3210a449a47d2f524e549f890fe9bd4bfa4ce97e90d4022d4655a8b0959998a5414d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
